name: Python application

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Set up Python 3.12
      uses: actions/setup-python@v7
      with:
        python-version: "3.12"
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install -y -c conda-forge python=3.12 gsl dftbplus
        python -m pip install --upgrade pip
        python -m pip install '.[test,lint]'
    - name: Lint with Pylint
      run: python -m pylint ThermoScreening
    - name: Test with pytest
      run: python -m pytest --cov=ThermoScreening --cov-report=xml
    - name: Build package
      run: |
        python -m pip install build
        python -m build

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: true
        flags: unittests
        verbose: true
